[req]
prompt = no
distinguished_name = subject
req_extensions = extensions

[subject]
CN = neuralng.dev

[extensions]
subjectAltName = @hostnames

[hostnames]
DNS.1 = neuralng.dev
DNS.2 = www.neuralng.dev
