import {
  contrastRatio,
  isHexColor,
  normalizeHex,
  setOklchLightness,
} from './color.js';
import { toKebabCase } from './naming.js';
import { resolvePrimaryPalette, resolveSurfacePalette } from './palettes.js';
import { getThemePresetQuality } from './preset-quality.js';
import type {
  NeuralThemeArtifacts,
  NeuralThemeCompileOptions,
  NeuralThemeContract,
  NeuralThemeDiagnostic,
  NeuralThemeModeRecipe,
  NeuralThemePresetDefinition,
  NeuralThemePresetName,
  NeuralThemePresetQuality,
  NeuralThemeRecipe,
  NeuralThemeSummary,
  NeuralThemeTokenContractEntry,
  NeuralThemeTokenValue,
} from './types.js';
import { validateThemeRecipeWithContract } from './validate-core.js';

const PALETTE_STEPS = [
  50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950,
] as const;
const MODE_TOKENS: Readonly<Record<string, string>> = {
  primary: '--neural-color-primary',
  surface: '--neural-color-surface',
  surfaceHover: '--neural-color-surface-hover',
  surfaceActive: '--neural-color-surface-active',
  text: '--neural-color-text',
  textStrong: '--neural-color-text-strong',
  textMuted: '--neural-color-text-muted',
  border: '--neural-color-border',
  borderHover: '--neural-color-border-hover',
  borderActive: '--neural-color-border-active',
  info: '--neural-color-info',
  success: '--neural-color-success',
  warning: '--neural-color-warning',
  danger: '--neural-color-error',
  error: '--neural-color-error',
};

export class NeuralThemeRecipeError extends Error {
  constructor(readonly diagnostics: readonly NeuralThemeDiagnostic[]) {
    super(
      `Invalid Neural theme recipe:\n${diagnostics
        .map((diagnostic) => `- ${diagnostic.path}: ${diagnostic.message}`)
        .join('\n')}`,
    );
    this.name = 'NeuralThemeRecipeError';
  }
}

export interface NeuralThemeCompilerAssets {
  readonly contract: NeuralThemeContract;
  readonly coreTemplate: string;
  readonly editorTemplate: string;
  readonly tailwindTemplate: string;
  readonly presets: Readonly<
    Record<NeuralThemePresetName, NeuralThemePresetDefinition>
  >;
}

export function compileThemeWithAssets(
  recipe: NeuralThemeRecipe,
  assets: NeuralThemeCompilerAssets,
  options: NeuralThemeCompileOptions = {},
): NeuralThemeArtifacts {
  const validation = validateThemeRecipeWithContract(recipe, assets.contract);
  if (!validation.valid)
    throw new NeuralThemeRecipeError(validation.diagnostics);

  const { contract, coreTemplate, editorTemplate, tailwindTemplate, presets } =
    assets;
  const presetName = recipe.extends ?? 'neutral';
  const preset = presets[presetName];
  const presetQuality = getThemePresetQuality(preset.id);
  const primary = resolvePrimaryPalette(
    recipe.color?.primary ?? preset.primary,
  );
  const surface = resolveSurfacePalette(
    recipe.color?.surface ?? preset.surface,
  );
  const baseOverrides = new Map<string, string>(
    Object.entries(preset.baseTokens),
  );
  const darkOverrides = new Map<string, string>(
    Object.entries(preset.darkTokens),
  );

  if (recipe.color?.primary !== undefined || presetName === 'neutral') {
    applyPalette(baseOverrides, 'primary', primary.palette);
  }
  if (recipe.color?.surface !== undefined || presetName === 'neutral') {
    applyPalette(baseOverrides, 'surface', surface.palette);
    baseOverrides.set('--neural-color-surface-0', '#ffffff');
  }
  applyStatusColors(recipe, baseOverrides, darkOverrides);
  applyTypography(recipe, contract, baseOverrides);
  applyShape(recipe, contract, baseOverrides, darkOverrides);
  applyDensity(recipe, baseOverrides);
  applyElevation(recipe, contract, baseOverrides);
  applyMotion(recipe, contract, baseOverrides);
  applyMode(recipe.modes?.light, baseOverrides);
  if (recipe.modes?.dark !== 'auto')
    applyMode(recipe.modes?.dark, darkOverrides);
  applyComponentOverrides(recipe, contract, baseOverrides);
  applyAdvancedOverrides(recipe, contract, baseOverrides);

  const includeTailwind =
    options.includeTailwind ?? recipe.output?.tailwind ?? true;
  const themeName = recipe.name;
  let sourceCss =
    [
      `/* Generated by @neural-ng/theme from compact recipe ${JSON.stringify(themeName)}. */`,
      replaceThemeName(coreTemplate, themeName),
      replaceThemeName(editorTemplate, themeName),
      renderOverrideBlock(themeName, baseOverrides, options.scope),
      renderDarkOverrideBlock(themeName, darkOverrides, options.scope),
      includeTailwind ? tailwindTemplate.trim() : '',
    ]
      .filter(Boolean)
      .join('\n\n')
      .replace(/\n{3,}/g, '\n\n')
      .trimEnd() + '\n';
  if (options.scope === 'theme') sourceCss = scopeThemeOnly(sourceCss);

  const summary = createSummary(
    recipe,
    preset,
    contract,
    recipe.color?.primary ?? preset.primary,
    recipe.color?.surface ?? preset.surface,
    baseOverrides,
    presetQuality,
  );
  const diagnostics = createCompileDiagnostics(
    resolveDiagnosticColor(
      baseOverrides,
      '--neural-color-primary-600',
      primary.palette[600],
    ),
    resolveDiagnosticColor(
      baseOverrides,
      '--neural-color-surface-50',
      surface.palette[50],
    ),
    resolveDiagnosticColor(
      darkOverrides,
      '--neural-color-primary-400',
      primary.palette[400],
    ),
    resolveDiagnosticColor(
      darkOverrides,
      '--neural-color-surface-950',
      surface.palette[950],
    ),
    presetQuality.minimumPrimarySurfaceContrast,
  );
  const tokenDocument = createTokenDocument(
    contract,
    baseOverrides,
    darkOverrides,
    summary,
  );
  const reportDocument = createReportDocument(
    contract,
    recipe,
    summary,
    diagnostics,
  );

  return {
    name: themeName,
    css: sourceCss,
    tokens: `${JSON.stringify(tokenDocument, null, 2)}\n`,
    report: `${JSON.stringify(reportDocument, null, 2)}\n`,
    types: createTypes(themeName),
    enabledOutputs: {
      tokens: recipe.output?.tokens ?? true,
      report: recipe.output?.report ?? true,
      types: recipe.output?.types ?? true,
    },
    summary,
  };
}

function applyPalette(
  overrides: Map<string, string>,
  family: 'primary' | 'surface',
  palette: Readonly<Record<number, string>>,
): void {
  for (const step of PALETTE_STEPS) {
    overrides.set(`--neural-color-${family}-${step}`, palette[step]);
  }
}

function applyStatusColors(
  recipe: NeuralThemeRecipe,
  base: Map<string, string>,
  dark: Map<string, string>,
): void {
  const colors = recipe.color;
  if (!colors) return;
  const entries = [
    ['info', colors.info],
    ['success', colors.success],
    ['warning', colors.warning],
    ['error', colors.error ?? colors.danger],
  ] as const;
  const neutralDefaults: Readonly<Record<string, string>> = {
    info: '#0284c7',
    success: '#16a34a',
    warning: '#ca8a04',
    error: '#dc2626',
  };
  for (const [name, value] of entries) {
    if (!value) continue;
    const normalized = normalizeHex(value);
    if (normalized === neutralDefaults[name]) continue;
    base.set(`--neural-color-${name}`, normalized);
    dark.set(
      `--neural-color-${name}`,
      setOklchLightness(normalized, name === 'warning' ? 0.82 : 0.72),
    );
  }
}

function applyTypography(
  recipe: NeuralThemeRecipe,
  contract: NeuralThemeContract,
  overrides: Map<string, string>,
): void {
  if (recipe.typography?.sans)
    overrides.set('--neural-font-family', recipe.typography.sans);
  if (recipe.typography?.mono)
    overrides.set('--neural-font-family-mono', recipe.typography.mono);
  const multiplier =
    recipe.typography?.scale === 'compact'
      ? 0.94
      : recipe.typography?.scale === 'large'
        ? 1.08
        : 1;
  if (multiplier === 1) return;
  for (const token of contract.tokens) {
    if (!token.name.includes('font-size')) continue;
    const value = token.modes.base;
    if (!value) continue;
    const scaled = scaleCssLengths(value, multiplier, true);
    if (scaled !== value) overrides.set(token.name, scaled);
  }
}

function applyShape(
  recipe: NeuralThemeRecipe,
  contract: NeuralThemeContract,
  base: Map<string, string>,
  dark: Map<string, string>,
): void {
  const radius = recipe.shape?.radius;
  if (radius && radius !== 'medium') {
    for (const token of contract.tokens) {
      if (!token.name.endsWith('-radius')) continue;
      const value = token.modes.base;
      if (!value || isPillRadius(value)) continue;
      base.set(token.name, resolveRadius(value, radius));
    }
  }
  switch (recipe.shape?.border) {
    case 'none':
      base.set('--neural-color-border', 'transparent');
      base.set('--neural-color-border-hover', 'transparent');
      base.set('--neural-color-border-active', 'transparent');
      dark.set('--neural-color-border', 'transparent');
      dark.set('--neural-color-border-hover', 'transparent');
      dark.set('--neural-color-border-active', 'transparent');
      break;
    case 'subtle':
      base.set('--neural-color-border', 'var(--neural-color-surface-200)');
      base.set(
        '--neural-color-border-hover',
        'var(--neural-color-surface-300)',
      );
      base.set(
        '--neural-color-border-active',
        'var(--neural-color-surface-400)',
      );
      dark.set('--neural-color-border', 'var(--neural-color-surface-800)');
      dark.set(
        '--neural-color-border-hover',
        'var(--neural-color-surface-700)',
      );
      dark.set(
        '--neural-color-border-active',
        'var(--neural-color-surface-600)',
      );
      break;
    case 'strong':
      base.set('--neural-color-border', 'var(--neural-color-surface-400)');
      base.set(
        '--neural-color-border-hover',
        'var(--neural-color-surface-500)',
      );
      base.set(
        '--neural-color-border-active',
        'var(--neural-color-surface-600)',
      );
      dark.set('--neural-color-border', 'var(--neural-color-surface-600)');
      dark.set(
        '--neural-color-border-hover',
        'var(--neural-color-surface-500)',
      );
      dark.set(
        '--neural-color-border-active',
        'var(--neural-color-surface-400)',
      );
      break;
    default:
      break;
  }
}

function applyDensity(
  recipe: NeuralThemeRecipe,
  overrides: Map<string, string>,
): void {
  const density = recipe.density ?? 'comfortable';
  if (density === 'comfortable') return;
  const values = {
    compact: ['0.875', '2rem', '0.375rem', '0.75rem', '0.375rem'],
    comfortable: ['1', '2.5rem', '0.625rem', '1rem', '0.5rem'],
    spacious: ['1.125', '3rem', '0.75rem', '1.25rem', '0.625rem'],
  }[density];
  const [factor, height, block, inline, gap] = values;
  overrides.set('--neural-density-factor', factor);
  overrides.set('--neural-control-height', height);
  overrides.set('--neural-control-padding-block', block);
  overrides.set('--neural-control-padding-inline', inline);
  overrides.set('--neural-control-gap', gap);
  for (const name of [
    'button',
    'input',
    'input-number',
    'select',
    'textarea',
  ]) {
    if (name === 'button') {
      overrides.set(
        '--neural-button-padding',
        'var(--neural-control-padding-block) var(--neural-control-padding-inline)',
      );
      overrides.set('--neural-button-gap', 'var(--neural-control-gap)');
    } else if (name === 'textarea') {
      overrides.set(
        '--neural-textarea-padding',
        'var(--neural-control-padding-block) var(--neural-control-padding-inline)',
      );
    } else {
      overrides.set(
        `--neural-${name}-min-height`,
        'var(--neural-control-height)',
      );
      overrides.set(
        `--neural-${name}-padding`,
        'var(--neural-control-padding-block) var(--neural-control-padding-inline)',
      );
    }
  }
  overrides.set('--neural-select-trigger-gap', 'var(--neural-control-gap)');
  overrides.set('--neural-select-value-gap', 'var(--neural-control-gap)');
}

function applyElevation(
  recipe: NeuralThemeRecipe,
  contract: NeuralThemeContract,
  overrides: Map<string, string>,
): void {
  const elevation = recipe.elevation ?? 'soft';
  if (elevation === 'soft' || elevation === 'default') return;
  for (const token of contract.tokens) {
    if (
      !token.name.includes('shadow') ||
      token.name === '--neural-color-shadow'
    )
      continue;
    const value = token.modes.base;
    if (!value) continue;
    if (elevation === 'none') {
      overrides.set(token.name, 'none');
    } else if (elevation === 'strong') {
      overrides.set(
        token.name,
        value.replace(
          /\/\s*(0?\.\d+)\)/g,
          (_, alpha: string) =>
            `/ ${Math.min(0.6, Number(alpha) * 1.35)
              .toFixed(3)
              .replace(/0+$/, '')
              .replace(/\.$/, '')})`,
        ),
      );
    }
  }
}

function applyMotion(
  recipe: NeuralThemeRecipe,
  contract: NeuralThemeContract,
  overrides: Map<string, string>,
): void {
  const motion = recipe.motion ?? 'default';
  if (motion === 'default') return;
  const multiplier = motion === 'fast' ? 0.75 : motion === 'slow' ? 1.25 : 0;
  for (const token of contract.tokens) {
    const value = token.modes.base;
    if (!value) continue;
    if (motion === 'reduced' && token.name.includes('transition')) {
      overrides.set(token.name, 'none');
    } else if (
      token.name.endsWith('-duration') ||
      token.name.includes('transition')
    ) {
      overrides.set(token.name, scaleDurations(value, multiplier));
    }
  }
}

function applyMode(
  mode: NeuralThemeModeRecipe | undefined,
  overrides: Map<string, string>,
): void {
  if (!mode) return;
  for (const [name, value] of Object.entries(mode)) {
    const token = MODE_TOKENS[name];
    if (token && value) overrides.set(token, normalizeHex(value));
  }
}

function applyComponentOverrides(
  recipe: NeuralThemeRecipe,
  contract: NeuralThemeContract,
  overrides: Map<string, string>,
): void {
  const known = new Set(contract.tokens.map((token) => token.name));
  for (const [component, values] of Object.entries(recipe.components ?? {})) {
    const normalizedComponent = toKebabCase(component);
    for (const [property, value] of Object.entries(values)) {
      const token = `--neural-${normalizedComponent}-${toKebabCase(property)}`;
      if (known.has(token))
        overrides.set(token, resolveTokenValue(value, known));
    }
  }
}

function applyAdvancedOverrides(
  recipe: NeuralThemeRecipe,
  contract: NeuralThemeContract,
  overrides: Map<string, string>,
): void {
  const known = new Set(contract.tokens.map((token) => token.name));
  for (const [token, value] of Object.entries(recipe.tokens ?? {})) {
    if (known.has(token)) overrides.set(token, resolveTokenValue(value, known));
  }
}

function resolveTokenValue(
  value: NeuralThemeTokenValue,
  known: ReadonlySet<string>,
): string {
  if (typeof value === 'number') return String(value);
  return value.replace(/\{([^}]+)\}/g, (_match, path: string) => {
    const token = aliasToToken(path.trim());
    if (!known.has(token) && !token.startsWith('--neural-color-')) {
      throw new Error(`Unknown token alias {${path}}.`);
    }
    return `var(${token})`;
  });
}

function aliasToToken(path: string): string {
  if (path.startsWith('--neural-')) return path;
  const parts = path.split('.').filter(Boolean);
  if (parts[0] === 'components') parts.shift();
  if (parts[0] === 'color') {
    return `--neural-color-${parts.slice(1).map(toKebabCase).join('-')}`;
  }
  return `--neural-${parts.map(toKebabCase).join('-')}`;
}

function replaceThemeName(css: string, name: string): string {
  return css
    .split("data-neural-theme='neutral'")
    .join(`data-neural-theme='${name}'`)
    .split('NeuralNg neutral')
    .join(`NeuralNg generated ${name}`)
    .split('neutral theme')
    .join(`${name} theme`);
}

function renderOverrideBlock(
  name: string,
  overrides: ReadonlyMap<string, string>,
  scope: NeuralThemeCompileOptions['scope'],
): string {
  if (overrides.size === 0) return '';
  const selector =
    scope === 'theme'
      ? `[data-neural-theme='${name}']`
      : `:root, [data-neural-theme='${name}']`;
  return `:where(${selector}) {\n${renderDeclarations(overrides)}\n}`;
}

function renderDarkOverrideBlock(
  name: string,
  overrides: ReadonlyMap<string, string>,
  scope: NeuralThemeCompileOptions['scope'],
): string {
  if (overrides.size === 0) return '';
  const selectors =
    scope === 'theme'
      ? `  [data-neural-mode='dark'][data-neural-theme='${name}'],\n  [data-neural-mode='dark'] [data-neural-theme='${name}']`
      : `  :root[data-neural-mode='dark'],\n  [data-neural-mode='dark'][data-neural-theme='${name}'],\n  [data-neural-mode='dark'] [data-neural-theme='${name}']`;
  return `:where(\n${selectors}\n) {\n${renderDeclarations(overrides)}\n}`;
}

function scopeThemeOnly(css: string): string {
  return css.replace(
    /:where\(([^)]*)\)/g,
    (selectorList, selectors: string) => {
      if (!selectors.includes(':root')) return selectorList;

      const scopedSelectors = selectors
        .split(',')
        .map((selector) => selector.trim())
        .filter((selector) => !selector.startsWith(':root'));

      return `:where(${scopedSelectors.join(', ')})`;
    },
  );
}

function renderDeclarations(overrides: ReadonlyMap<string, string>): string {
  return [...overrides.entries()]
    .sort(([left], [right]) => left.localeCompare(right, 'en'))
    .map(([name, value]) => `  ${name}: ${value};`)
    .join('\n');
}

function resolveRadius(baseValue: string, radius: string): string {
  if (!['none', 'small', 'medium', 'large', 'xlarge'].includes(radius))
    return radius;
  if (radius === 'none') return '0';
  const profiles = {
    small: ['0.125rem', '0.25rem', '0.375rem', '0.5rem'],
    medium: ['0.25rem', '0.375rem', '0.5rem', '0.75rem'],
    large: ['0.375rem', '0.5rem', '0.75rem', '1rem'],
    xlarge: ['0.5rem', '0.75rem', '1rem', '1.25rem'],
  } as const;
  const numeric = parseFloat(baseValue);
  const tier = numeric <= 0.3 ? 0 : numeric <= 0.5 ? 1 : numeric <= 0.8 ? 2 : 3;
  return profiles[radius as keyof typeof profiles][tier];
}

function isPillRadius(value: string): boolean {
  return value.includes('%') || /(?:999|1000)\d*px/.test(value);
}

function scaleCssLengths(
  value: string,
  multiplier: number,
  remOnly = false,
): string {
  return value.replace(
    /(-?\d*\.?\d+)(rem|px)/g,
    (match, amount: string, unit: string) => {
      if (remOnly && unit !== 'rem') return match;
      return `${formatNumber(Number(amount) * multiplier)}${unit}`;
    },
  );
}

function scaleDurations(value: string, multiplier: number): string {
  if (multiplier === 0) return value.replace(/\d*\.?\d+(ms|s)/g, '0ms');
  return value.replace(
    /(\d*\.?\d+)(ms|s)/g,
    (_match, amount: string, unit: string) =>
      `${formatNumber(Number(amount) * multiplier)}${unit}`,
  );
}

function formatNumber(value: number): string {
  return Number(value.toFixed(4)).toString();
}

function createSummary(
  recipe: NeuralThemeRecipe,
  preset: NeuralThemePresetDefinition,
  contract: NeuralThemeContract,
  primary: string,
  surface: string,
  overrides: ReadonlyMap<string, string>,
  quality: NeuralThemePresetQuality,
): NeuralThemeSummary {
  return {
    name: recipe.name,
    extends: preset.id,
    primary,
    surface,
    density: recipe.density ?? preset.density,
    radius: recipe.shape?.radius ?? preset.radius,
    elevation: recipe.elevation ?? preset.elevation,
    motion: recipe.motion ?? preset.motion,
    quality,
    modes: ['light', 'dark'],
    componentOverrides: Object.keys(recipe.components ?? {}).sort((a, b) =>
      a.localeCompare(b, 'en'),
    ),
    tokenOverrides: overrides.size,
    sourceHash: preset.sourceHash,
  };
}

function resolveDiagnosticColor(
  overrides: ReadonlyMap<string, string>,
  token: string,
  fallback: string,
): string {
  const value = overrides.get(token);
  return value && isHexColor(value) ? value : fallback;
}

function createCompileDiagnostics(
  lightPrimary: string,
  lightSurface: string,
  darkPrimary: string,
  darkSurface: string,
  minimumContrast: number,
): NeuralThemeDiagnostic[] {
  const diagnostics: NeuralThemeDiagnostic[] = [];
  const lightRatio = contrastRatio(lightPrimary, lightSurface);
  const darkRatio = contrastRatio(darkPrimary, darkSurface);
  if (lightRatio < minimumContrast)
    diagnostics.push({
      severity: 'warning',
      code: 'contrast.primary.light',
      path: 'color.primary',
      message: `Primary-to-surface contrast is ${lightRatio.toFixed(2)}:1 in light mode; the preset quality floor is ${minimumContrast.toFixed(2)}:1.`,
    });
  if (darkRatio < minimumContrast)
    diagnostics.push({
      severity: 'warning',
      code: 'contrast.primary.dark',
      path: 'color.primary',
      message: `Primary-to-surface contrast is ${darkRatio.toFixed(2)}:1 in dark mode; the preset quality floor is ${minimumContrast.toFixed(2)}:1.`,
    });
  return diagnostics;
}

function createTokenDocument(
  contract: NeuralThemeContract,
  baseOverrides: ReadonlyMap<string, string>,
  darkOverrides: ReadonlyMap<string, string>,
  summary: NeuralThemeSummary,
): object {
  const base = {} as Record<string, object>;
  const dark = {} as Record<string, object>;
  for (const token of contract.tokens) {
    const key = token.name.slice('--neural-'.length);
    const baseValue = baseOverrides.get(token.name) ?? token.modes.base;
    if (baseValue !== undefined) base[key] = dtcgToken(baseValue);
    const darkValue = darkOverrides.get(token.name) ?? token.modes.dark;
    if (darkValue !== undefined) dark[key] = dtcgToken(darkValue);
  }
  for (const [name, value] of baseOverrides) {
    const key = name.slice('--neural-'.length);
    base[key] ??= dtcgToken(value);
  }
  for (const [name, value] of darkOverrides) {
    const key = name.slice('--neural-'.length);
    dark[key] ??= dtcgToken(value);
  }
  return {
    $extensions: {
      'dev.neural-ng.theme': {
        recipeVersion: 1,
        generator: 'neural-oklch-v1',
        summary,
      },
    },
    neural: {
      base,
      modes: { dark },
    },
  };
}

function dtcgToken(value: string): object {
  return {
    $type: isHexColor(value) ? 'color' : 'string',
    $value: value.replace(
      /var\((--neural-[a-z0-9-]+)\)/gi,
      (_match, token: string) =>
        `{neural.base.${token.slice('--neural-'.length)}}`,
    ),
  };
}

function createReportDocument(
  contract: NeuralThemeContract,
  recipe: NeuralThemeRecipe,
  summary: NeuralThemeSummary,
  diagnostics: readonly NeuralThemeDiagnostic[],
): object {
  return {
    valid: !diagnostics.some((diagnostic) => diagnostic.severity === 'error'),
    theme: summary,
    diagnostics,
    contract: contract.stats,
    output: {
      css: `${recipe.name}.css`,
      tokens: `${recipe.name}.tokens.json`,
      report: `${recipe.name}.report.json`,
      types: `${recipe.name}.d.ts`,
    },
  };
}

function createTypes(name: string): string {
  return `/** Generated by @neural-ng/theme. */\nexport type NeuralGeneratedTheme = ${JSON.stringify(name)};\nexport declare const neuralThemeName: NeuralGeneratedTheme;\n`;
}
