export {
  getCatalogSourceHash,
  getComponentContract,
  getPackageCatalog,
  listComponents,
  listThemes,
  recommendComponents,
  searchComponents,
} from './catalog.js';
export { listNeuralResources, readNeuralResource } from './resources.js';
export { planUi } from './composition.js';
export { getIconCatalog, getIconCatalogSummary, searchIcons } from './icons.js';
export { validateUsage } from './validation.js';
export { inspectNeuralProject, suggestConsistentUi } from './project.js';
export { createNeuralMcpServer, serveNeuralMcpStdio } from './server.js';
export {
  compileThemeRecipeJson,
  createThemeRecipe,
  diffThemeRecipeJson,
  editThemeRecipeJson,
  formatJson as formatThemeJson,
  getThemeComponentContract,
  listThemeComponentIds,
  loadNeuralThemeRuntime,
  NEURAL_THEME_AI_GUIDE,
  NEURAL_THEME_SCHEMA_GUIDE,
  NEUTRAL_THEME_RECIPE,
  parseThemeRecipeJson,
  validateThemeRecipeJson,
} from './theme.js';
export type {
  NeuralCatalogKind,
  NeuralComponentContract,
  NeuralComponentExample,
  NeuralComponentInput,
  NeuralComponentMethod,
  NeuralCompositionComponent,
  NeuralCompositionKind,
  NeuralCompositionPlan,
  NeuralCompositionRequest,
  NeuralCompositionSection,
  NeuralComponentModel,
  NeuralComponentOutput,
  NeuralComponentProvider,
  NeuralComponentResources,
  NeuralComponentTemplate,
  NeuralPackageCatalog,
  NeuralIconCatalog,
  NeuralIconCatalogEntry,
  NeuralIconCategory,
  NeuralIconContract,
  NeuralIconSearchMatch,
  NeuralIconSearchResult,
  NeuralIconStyle,
  NeuralResourceContents,
  NeuralResourceDescriptor,
  NeuralSearchMatch,
  NeuralThemeCatalogEntry,
  NeuralTypeAliasContract,
  NeuralProviderRequirement,
  NeuralConsistentUiSuggestion,
  NeuralProjectComponentUsage,
  NeuralProjectDiagnostic,
  NeuralProjectInspection,
  NeuralUsageDiagnostic,
  NeuralUsageDiagnosticSeverity,
  NeuralUsageValidationRequest,
  NeuralUsageValidationResult,
} from './types.js';

export type {
  NeuralThemeArtifacts,
  NeuralThemeDiagnostic,
  NeuralThemeRecipe,
  NeuralThemeRecipeCreateInput,
  NeuralThemeRecipeDiffEntry,
  NeuralThemeRecipePatch,
  NeuralThemeRuntime,
  NeuralThemeSummary,
  NeuralThemeTokenContractEntry,
  NeuralThemeValidationResult,
} from './theme.js';
